name: ess_pdf_processor
description: IPSC ESS PDF processor - dart-only PoC for text extraction and parsing
version: 0.0.1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  pdf: ^3.10.7
  csv: ^5.1.1
  http: ^0.13.6
  html: ^0.15.0

dev_dependencies:
  test: ^1.21.0
