name: web_app
description: Minimal Flutter web app for ess_pdf_processor PDF.js browser extractor
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ess_pdf_processor:
    path: ../
  universal_html: ^2.0.8
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
